export const CHANGE_CLASS_MENU_SERVICE = 'CHANGE_CLASS_MENU_SERVICE';
export const CHANGE_LIST_SALES_HITS = 'CHANGE_LIST_SALES_HITS';
export const CHANGE_LIST_SALES_SPLICE = 'CHANGE_LIST_SALES_SPLICE';
export const CHANGE_CLASS_MENU_CATALOG_SERVICE = 'CHANGE_CLASS_MENU_CATALOG_SERVICE';
export const CHANGE_LIST_SALES_SPLICE_ALL_CATALOG_SERVICE = 'CHANGE_LIST_SALES_SPLICE_ALL_CATALOG_SERVICE';
export const CHANGE_ACTIVE_ID_CATALOG_SERVICE = 'CHANGE_ACTIVE_ID_CATALOG_SERVICE';
export const ADD_PRODUCT_IN_CART_SERVICE = 'ADD_PRODUCT_IN_CART_SERVICE';
export const REMOVE_PRODUCT_OF_CART_SERVICE = 'REMOVE_PRODUCT_OF_CART_SERVICE';